name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.0

      - name: Test
        run: go test -v ./...

      - name: Set up gox
        run: go install github.com/mitchellh/gox@latest
        if: startsWith(github.ref, 'refs/tags/')

      - name: Build
        run: gox -osarch="linux/arm linux/amd64 darwin/amd64 windows/amd64" -output=dist/"{{.Dir}}_{{.OS}}_{{.Arch}}/{{.Dir}}" -ldflags "-X github.com/${GITHUB_REPOSITORY}/cmd.appName=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/} -X github.com/${GITHUB_REPOSITORY}/cmd.version=`git rev-parse --short HEAD`"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Zip
        run: |
          mkdir -p release
          for arch in $(ls dist); do cd "dist/${arch}" && zip "../../release/${arch}.zip" * && cd -; done
        if: startsWith(github.ref, 'refs/tags/')

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
